### ISSUE TITLE
TCCoaster Animation Bugs

### ISSUE THREAD

**Issue by JustKatze** [bergerhealer/TC-Coasters#12]
TCCoaster Version: Last Build
TrainCarts v1.14.4-v2-SNAPSHOT (build:552)
BkcommonLib v1.14.4-v2-SNAPSHOT (build:657)

Bugs:
https://streamable.com/18oga
https://streamable.com/wqc92
https://streamable.com/xrgbu

**Comment by bergerkiller** [comment]
Can you confirm whether these issues still exist in the latest development builds of BKC, Traincarts and TC-Coasters? ( 1.15.2-v1-SNAPSHOT )

**Comment by bbayu123** [comment]
Closing issue, stale, resolution unknown.
