### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by Wh1spr** [bergerhealer/TC-Coasters#13]
The PlotSquared dependency that is being used hasn't been available in a while. Please start using v5, which is now the only available version.

For precise info, take a look at this link, which is the official wiki: 
https://wiki.intellectualsites.com/en/plotsquared/developer/development-portal#maven-plotsquared-core

**Comment by bergerkiller** [comment]
See: https://github.com/bergerhealer/TC-Coasters/commit/59aecf74647395d75bddf7af8b05e946dc351808

Are there remaining issues with these changes? I noticed in your PR you also changed the repository for WorldEdit, is this important?

**Comment by bergerkiller** [comment]
It does look like v4 is incompatible with Minecraft 1.16 though, so this v4 support will only be important for those on Minecraft 1.15.2 or earlier (which tcc does support)

**Comment by Wh1spr** [comment]
I changed the WorldEdit repository as was described in the wiki. I have checked the two repositories and they seem to contain the same files.

**Comment by bergerkiller** [comment]
There are also no imports for WorldEdit, so perhaps that dependency isn't really needed in the pom.xml to begin with. I can't really test v5 support (as I dont have plotsquared v5 myself), so I'll need confirmation from someone that does that this actually works now.

**Comment by Wh1spr** [comment]
_Now, I did do my research before I suggested the changes_

_The WorldEdit repository is necessary, as said in PlotSquared's wiki:_ 
![image](https://user-images.githubusercontent.com/14895860/87257950-a8db2600-c49f-11ea-9b9f-68a4d43ae194.png)

_The 4.400 version of plotsquared is no longer available anywhere:_
![image](https://user-images.githubusercontent.com/14895860/87257959-ce682f80-c49f-11ea-8a45-3463bdafb549.png)

_And the repository itself is no longer available either:_
![image](https://user-images.githubusercontent.com/14895860/87257965-ea6bd100-c49f-11ea-8dda-e0330bc32cda.png)

**Comment by bergerkiller** [comment]
Hm, which means either I add the v4 project to our jenkins CI, or I include the v4 lib jar to the project. I guess the jar files were cached which is why it all works fine for now.

**Comment by bbayu123** [comment]
Closing issue, no longer relevant - all dependencies are now available in our [Jenkins CI Maven Repository](https://ci.mg-dev.eu/plugin/repository/#/).
