### ISSUE TITLE
bug slowdown true

### ISSUE THREAD

**Issue by GwnJernoow** [bergerhealer/TC-Coasters#15]
Hi,

Slowdown true isn't working anymore for me, it's just like
the train is ignoring the sign... Because the other signs are working.

Can this be fixed??

-GwnJernoow

**Comment by Andre601** [comment]
Please provide actual information such as the server version you use (`/version`) and the TCC, TC and BKCommonLib versions (`/tcc version`)

Additionally should explain in detail what you try to do and what steps you need to take in order to actually reproduce this bug.

**Comment by GwnJernoow** [comment]
Server version: PaperMC 1.15.2
Tcc version: 1.16.1 -v1
Bkcommonlib version: 1.16.1 -v1
Traincarts version: 1.16.1 -v1

**Comment by Andre601** [comment]
This doesn't seem to be right. Please use the commands I mentioned as they give the exact versions (including builds)

**Comment by GwnJernoow** [comment]
https://gyazo.com/09f78fdce98841c2d9cfe4bf88c88a5c

**Comment by bbayu123** [comment]
Closing issue, stale, outdated, resolution unknown
