### ISSUE TITLE
1.17 NullPointer

### ISSUE THREAD

**Issue by stijnb1234** [bergerhealer/TC-Coasters#18]
I get a NullPointer on 1.17.1 when I let a train move on a TCCoasters track.

Running BKCommonLib 1.17.1-v1, build 1094. TrainCarts 1.17.1-v1, build 932. TCCoasters 1.17.1-v1, build 208.
My server is running PaperSpigot 1.17.1, build 154.

**Logs:**
https://pastebin.com/WEtFC9ur

**Comment by bergerkiller** [comment]
See if this fixes it https://ci.mg-dev.eu/job/TC%20Coasters/209/

**Comment by stijnb1234** [comment]
Seems to have solved it. Thanks!
