### ISSUE TITLE
tracks

### ISSUE THREAD

**Issue by mitchngwen** [bergerhealer/TC-Coasters#19]
Pitch, yaw and roll appear to do nothing. I can not figure out how to make the tracks follow the line. It would be super cool if it would auto add tracks that line up with your track line.

**Comment by bergerkiller** [comment]
You mean the rotation/orientation thing? Thats for the little stick orientation. All that configures is the roll around the rail that is the 'up' direction of the cart when it is on the rails. There is no builtin command to 'rotate' track at the moment.

There is /tcc pos x/y/z align and average and a few others, that makes multiple nodes have the same position along an axis.

**Comment by bbayu123** [comment]
Closing issue, stale, unclear what "follow the line" even means, plus a suggestion has been provided.
