### ISSUE TITLE
Roller coasters disappear

### ISSUE THREAD

**Issue by wesley9946** [bergerhealer/TC-Coasters#2]
Hi there,

Everytime I reload the server, all of the roller coasters disappear.
Can you fix it?

**Comment by Ryan7214** [comment]
Do you reload or restart your server?

**Comment by wesley9946** [comment]
Reloading it with /reload

**Comment by mio9** [comment]
No matter what, doing `/reload` in a server would break most of the thing, *restart* your server instead

**Comment by Ryan7214** [comment]
First of all, reloading is bad for your server, and the second thing is that plugins can get broken if you reload. You can probably solve this problem by restarting.

**Comment by wesley9946** [comment]
Alright, thanks for your time!

**Comment by mio9** [comment]
if the problem is resolved, please consider closing this issue , thanks :D
