### ISSUE TITLE
Vivecraft Automatic Vehicle Rotation in latest update

### ISSUE THREAD

**Issue by ABrokenTV** [bergerhealer/TC-Coasters#21]
When Vehicle Rotation is On in Vivecraft, the view spins around on its own, even when the train isn't in motion. You can experience the issue on main.mcparks.us, and owner updated it 4 months ago. Before said update, the vehicle rotation was working, but I don't know what version they were on.

**Comment by bbayu123** [comment]
We're not associated with Vivecraft in any way, and we don't know their versions.
There has been a lot of development over the past 4 months, so their versions are most likely very outdated by now.
They will need to update first. If it's still an issue, ask them to provide Minecraft Server version (including type and build number), BKCommonLib version (including build number), TrainCarts version (including build number), TC-Coasters version (including build number), any console error messages if applicable, and if possible, a minimum reproducible setup.

**Comment by bergerkiller** [comment]
Its also important to know what seat view lock modes are used for those carts

**Comment by bbayu123** [comment]
Closing issue, unrelated to TC-Coasters.
