### ISSUE TITLE
Node signs no longer work in 1.20.1

### ISSUE THREAD

**Issue by amalon** [bergerhealer/TC-Coasters#25]
I'm sure I could previously hold a sign in my hand and right click on a tccoaster node to add a sign to it. Left clicking removes existing signs, but I can't add them back with right click any longer. When I right click I get a momentary "Edit Sign Message", but then its gone. Perhaps something broke with the recent signs update which allows signs to be edited?

[16:36:03 INFO]: TCCoasters: v1.20.1-v1 (build: 311)
[16:36:03 INFO]: TrainCarts: v1.20.1-v1 (build: 1412)
[16:36:03 INFO]: BKCommonLib: v1.20.1-v1 (build: 1586)
[16:36:03 INFO]: Server: git-Paper-65 (MC: 1.20.1)

**Comment by bergerkiller** [comment]
This was fixed in the dev of bkcl (the edit dialog not showing up) https://ci.mg-dev.eu/job/BKCommonLib/1593/

**Comment by amalon** [comment]
ah okay, great. I'll try that. Apologies for the noise.
Thanks, J

**Comment by amalon** [comment]
and the train through portal crash is fixed with that (that was the next thing I was going to report). Thanks!

**Comment by bergerkiller** [comment]
Update traincarts and bkcl and (cross-world) portal teleport bugs are fixed too yeah
