### ISSUE TITLE
Some junctions lose setting on reload

### ISSUE THREAD

**Issue by amalon** [bergerhealer/TC-Coasters#26]
I have a number of TCC junctions that won't reload in the same position they are saved in. So after tweaking the coaster tracks a bunch of trains go off in the wrong directions and get messed up.

For example, this junction keeps going back to 1->2. I've set it to 1->3, and then done `/tcc save`:
![2023-09-17_12 27 36](https://github.com/bergerhealer/TC-Coasters/assets/210303/cc5f75c5-ce3a-44ac-afb5-7e1808ed7bde)

I've found the coaster4.csv that contains this bit of track, and when I diff it, I can see that there is a change in the order of the LINK entries, from 1, 2, 3 to  3, 1, 2
```diff
--- /home/james/coaster4.csv    2023-09-17 12:05:58.053813383 +0100
+++ coaster4.csv        2023-09-17 12:27:34.577245735 +0100
@@ -4,9 +4,9 @@
 "LINK","241.5","62.979712","-695.218725"
 "ROOT","227.5","62.9375","-730.5","0.0","1.0","0.0"
 "SIGN","LINES","HELLO","","",""
+"LINK","227.505492","63.0","-697.697875"
 "LINK","227.5","62.9375","-732.5"
 "LINK","228.503084","62.9375","-726.500768"
-"LINK","227.505492","63.0","-697.697875"
 "ROOT","217.5","62.9375","-240.0625","0.0","1.0","0.0"
 "LINK","224.0625","62.9375","-259.5"
 "LINK","212.717656","62.937985","-225.781616"
```

When I then to `/tcc reload`, it switches back to 1->2:
![2023-09-17_12 28 00](https://github.com/bergerhealer/TC-Coasters/assets/210303/d0a11a24-7c03-4bc9-a718-e44efafd5ba4)

The same happens if I set 2->3.

TCCoasters: v1.20.1-v2-SNAPSHOT (build: 322)
TrainCarts: v1.20.1-v3-SNAPSHOT (build: 1444)
BKCommonLib: v1.20.1-v3-SNAPSHOT (build: 1605)
Server: git-Paper-65 (MC: 1.20.1)

I've observed this issue for quite a long time now, though I had managed to work around it by deleting nodes and recreating junctions, which is ofc a pain.

I've also attempted to recreate on a new bit of track, without success.

**Comment by bergerkiller** [comment]
Can you /tcc export the junction and some of the neighbouring nodes? Then I can simulate and test it on my end as well

(or send the affected coaster4.csv file)

**Comment by amalon** [comment]
I did /tcc export of the nodes around it, and it gave me this link: https://paste.traincarts.net/onoxopinef

Give me a shout if you want the full csv. its only 11K / 194 lines (I'm surprised it isn't bigger to be honest since its well connected).

**Comment by bergerkiller** [comment]
I think Ill need the full csv as the problem doesnt occur with just that portion of track and doing /tcc save and /tcc reload. In your 'change diff' it showed two junction roots in a row and I think the issue lies here

**Comment by amalon** [comment]
Here's that file:
[coaster4.csv](https://github.com/bergerhealer/TC-Coasters/files/12642803/coaster4.csv)

(are the coaster csv files independent of one another?)

**Comment by bergerkiller** [comment]
For the most part they are, but they can connect with each other as well.

**Comment by bergerkiller** [comment]
Ah yep and unfortunately thats the case here. The junction in question is connecting with another coaster file, possibly explaining why it isnt working.

I also need the coaster csv containing node:
`"227.505492","63.0","-697.697875"`

![2023-09-17_14 37 21](https://github.com/bergerhealer/TC-Coasters/assets/957601/6061ee40-3ca5-4c36-ab54-967842ad2b7a)

**Comment by amalon** [comment]
[coaster2.csv](https://github.com/bergerhealer/TC-Coasters/files/12642822/coaster2.csv)

**Comment by bergerkiller** [comment]
![2023-09-17_14 42 05](https://github.com/bergerhealer/TC-Coasters/assets/957601/88d14a6c-65c5-4e54-a44d-fe046871224c)
It loads in but for whatever reason I cant make it bug out changing this junction and doing /tcc save and /tcc reload. Also checked changing the junction and restarting the server, also remembers it then.

But knowing its an issue of a junction connecting to another coaster, Ill have a quick peek at the code if I can spot something

**Comment by amalon** [comment]
happy to zip up all the csv files for you if it might help (you've already got the biggest 2, but there are 11 others in that world).

**Comment by bergerkiller** [comment]
[tcc-test-swapped-conn.zip](https://github.com/bergerhealer/TC-Coasters/files/12642864/tcc-test-swapped-conn.zip)
I found one possible cause but I cant really test it myself as I dont have the issue, but you can check if it fixes the issue. Saves some time if it does
```
            // Ensure junction switching order is preserved
            // Note: the input link node A is the one that contains the junction, and whose junction
            //       selection order must be preserved. However, if the connection already existed,
            //       node A and node B might be swapped, so that must be accounted for.
            if (link.node_a.isReference(connection.getNodeA())) {
                connection.getNodeA().pushBackJunction(connection);
            } else {
                connection.getNodeB().pushBackJunction(connection);
            }
```
(Had to zip it because github doesnt allow jar files for some reason)

**Comment by amalon** [comment]
unfortunately the NO_CI version didn't fix it. Same behaviour observed.

**Comment by bergerkiller** [comment]
Well, maybe if you zip up all coasters I can at least reproduce it

**Comment by amalon** [comment]
I've zipped up the TCCoasters folder for the world in question:
[coasters.zip](https://github.com/bergerhealer/TC-Coasters/files/12642896/coasters.zip)

**Comment by bergerkiller** [comment]
That perfectly reproduced it. I select 1-3 and after /tcc reload its 1-2 again. :+1: 

I'll trim this down to a minimally reproducible dataset and figure out whats going wrong

**Comment by bergerkiller** [comment]
It was (randomly) loading in one coaster before another, so it couldn't create links in the right order because the other coaster's node didn't exist yet.

I've rewritten it so that it first loads all coaster's core nodes and connections in, and only after they are all loaded, does the linking up of junctions and inter-coaster connections.

That, combined with the fix I had earlier, finally fixed the issue completely.

~~https://ci.mg-dev.eu/job/TC%20Coasters/323/~~
One more minor fix needed 1 sec

**Comment by bergerkiller** [comment]
Okay now its good. https://ci.mg-dev.eu/job/TC%20Coasters/324/

**Comment by amalon** [comment]
working great so far. Thanks so much!
