### ISSUE TITLE
Long announcement signs don't work

### ISSUE THREAD

**Issue by amalon** [bergerhealer/TC-Coasters#27]
If I add multiple signs to a node, it doesn't behave the same as under a track block.

Under a track block, i can add signs below one another like this:
```
[+train]
announce
this is a 
very long
```
```
announcement
```

And it concatenates the announcement into "this is a very long announcement", but with tcc node signs with the same content on a single node, this doesn't seem to work. It just says "this is a very long".

```
TCCoasters: v1.20.2-v2-SNAPSHOT (build: 326)
TrainCarts: v1.20.2-v2-SNAPSHOT (build: 1496)
BKCommonLib: v1.20.2-v3-SNAPSHOT (build: 1652)
```

**Comment by bergerkiller** [comment]
config.yml has "message shortcuts" to put longer messages. Add an entry there, then put the entry name as text (no %) and itll replace it.

I'll check why the different tcc/tc signs exists tho

**Comment by bergerkiller** [comment]
Actually, did you add the sign with sneak (shift) + click? It should not show a red line between the signs or it wont work. Or use /tcc sign add and add any number of lines you want

**Comment by amalon** [comment]
that'll be it. with sneak click it works great (once I step back so as not to add a real sign). apologies for the noise!
