### ISSUE TITLE
Error message while editing a coaster

### ISSUE THREAD

**Issue by Geitenijs** [bergerhealer/TC-Coasters#3]
Got the following error message while I was dragging around a new track piece: https://pastebin.com/CyLijDwz
Everything worked fine though, I wouldn't have noticed if I didn't have the console open on my second screen.

Running Paper 1.13.2 build 488, TC build 432, BKC build 490 and TCC build 51.

**Comment by bergerkiller** [comment]
Ah those are always fun. It's because of the whole limitation where listening to packets must be done on the network thread, so it causes a bit of trouble there. I'll have to make the whole system more robust to multithreaded logic like this.

I hope it didn't cause any long-lasting issues though.

**Comment by bergerkiller** [comment]
I have finally properly corrected this. https://github.com/bergerhealer/TC-Coasters/commit/8e6445c497a1683a44b3840af11f10c9ab56f058

**Comment by Geitenijs** [comment]
Great, thanks!
