### ISSUE TITLE
Carts(Models) going in eachother

### ISSUE THREAD

**Issue by Kas-2** [bergerhealer/TC-Coasters#6]
When having much Nodes, you could have the problem that carts(With models) go in eachother randomly

**Comment by mio9** [comment]
Would you mind providing more details on the problem? for example
1. What you expect it to work
2. What it comes out instead
3. Version of BKCommonLib , TrainCarts and TC-Coaster
4. Version of Minecraft and server (including spigot, paper, or ~~craftbukkit[bukkit is strongly discouraged]~~)
5. Screenshot (if you can)

**Comment by Kas-2** [comment]
1: Trains not going in eachother, but just staying attached right like an real coaster train needs to.
2: It comed out like this: if i spawn 3 models, and just give them an little push, they attach, but if i "dispatch"(release out of an station sign) them, they go in eachother.

3: Latest Dev builds.
4: http://prntscr.com/ni9qj7

**Comment by mio9** [comment]
it seems like the problem of cart length, or incorrect collision policy. Do you mind taking a short video of it happening?

**Comment by kascodingNL** [comment]
If you want, you could join my server, but sure

**Comment by kascodingNL** [comment]
I am uploading the video at: https://youtu.be/XAS5g6SljH0

**Comment by kascodingNL** [comment]
Nice that i got an answer back by the way...
