### ISSUE TITLE
TC Coasters junctions/switchers

### ISSUE THREAD

**Issue by GwnJernoow** [bergerhealer/TC-Coasters#7]
Hey, I have problems with the junctions / switchers of tc coasters ... they work good above the ground and we are now working on the system of symbolica but below the ground the junctions do not work ... We're working with taggs for Music tour / hero tour etc .. But I tested the same above ground and there the switchers work just fine ... Can you help?

**Comment by bergerkiller** [comment]
Which version of TC-coasters are you using? If its the Spigot 1.13.2 release, you can use this build instead, which fixes an issue that the rails block of a switcher sign isnt saved. If you had changed the rail block of the junction then that would explain it. https://ci.mg-dev.eu/job/TC%20Coasters/53/

Another reason for it not working might be that the train doesn't "see" the switcher sign, in which case, try:
```
[+train:nesw]
switcher
```

(note the north-east-south-west trigger directions)

**Comment by GwnJernoow** [comment]
Aah, now it works! i used that [!train:nesw] and now the switchers work! TY for your help! :D
