### ISSUE TITLE
Rare bugg met station

### ISSUE THREAD

**Issue by GwnJernoow** [bergerhealer/TC-Coasters#9]
Ik ben bezig met symbolica en ik gebruik natuurlijk drie station signs bij het station maar op een of andere manier stoppen de fantasievaarders even met rijden als ze op een station gekomen zijn en daarna gaan ze door naar de plek waar ze echt moeten stoppen... Hoe zorg ik dat dit niet gebeurt?

**Comment by bergerkiller** [comment]
Oude issue ticket, maar ik geef nog maar wel even antwoord voor anderen die lezen. Ik vermoed dat dit of een bug was die sinds al gefixed was (discord discussie) of dat dit op te lossen is door met redstone ervoor te zorgen dat altijd maar 1 station per keer actief is. Met [train] als beide kanten een redstone signaal hebben, stopt de trein op het station. Als er geen redstone is, negeert de trein het station.
